#!/usr/bin/env bash
#
# Installs one AWG-RT node: the amnezia-awg2 (AmneziaWG 2.0) container
# plus the node-agent that the panel talks to.
#
# Run this ON THE NODE itself (e.g. my-awg-node), from inside the
# node-agent/ directory of this repo:
#
#   cd Vodkinnet-AWG-RT/node-agent
#   sudo ./install.sh
#
# Safe to re-run: if .env already exists, it is reused as-is (edit it
# by hand first if you need to change a value) rather than silently
# overwritten and regenerated with new secrets, which would break an
# already-registered node's agent_token in the panel.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

log()  { echo -e "\033[1;34m[install-node]\033[0m $*"; }
warn() { echo -e "\033[1;33m[install-node]\033[0m $*"; }
err()  { echo -e "\033[1;31m[install-node]\033[0m $*" >&2; }

# --- 1. Root check -----------------------------------------------------
# The amnezia-awg2 container needs --privileged + NET_ADMIN + SYS_MODULE,
# and installing Docker itself (if missing) needs root. No point
# pretending non-root is supported.
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (or with sudo)."
    exit 1
fi

# --- 2. Docker + Compose plugin check/install ---------------------------
if ! command -v docker &> /dev/null; then
    log "Docker not found — installing via get.docker.com convenience script."
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
else
    log "Docker already installed: $(docker --version)"
fi

if ! docker compose version &> /dev/null; then
    err "Docker is installed but the 'docker compose' plugin is missing."
    err "This usually means Docker was installed via a method that skips"
    err "the compose plugin — reinstall via get.docker.com, or install"
    err "docker-compose-plugin manually for your distro, then re-run this script."
    exit 1
fi
log "docker compose available: $(docker compose version --short)"

# --- 3. .env setup -------------------------------------------------------
if [ -f .env ]; then
    warn ".env already exists — reusing it as-is."
    warn "If you need to change AWG_LISTEN_PORT or regenerate AGENT_TOKEN,"
    warn "edit .env by hand, then re-run this script (it will only rebuild"
    warn "containers, not touch .env again)."
    # shellcheck disable=SC1091
    source .env
else
    log "No .env found — let's set one up."

    read -rp "Node name (for your own reference, e.g. my-awg-node): " NODE_NAME_INPUT
    read -rp "UDP port for AmneziaWG to listen on [55632]: " AWG_LISTEN_PORT_INPUT
    AWG_LISTEN_PORT_INPUT="${AWG_LISTEN_PORT_INPUT:-55632}"
    read -rp "Publicly reachable hostname/IP for this node (leave blank if the panel will supply it): " AWG_PUBLIC_ENDPOINT_INPUT

    GENERATED_TOKEN="$(openssl rand -hex 32)"

    cat > .env << EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Node: ${NODE_NAME_INPUT}

AGENT_TOKEN=${GENERATED_TOKEN}
AWG_CONTAINER_NAME=amnezia-awg2
AWG_LISTEN_PORT=${AWG_LISTEN_PORT_INPUT}
AWG_PUBLIC_ENDPOINT=${AWG_PUBLIC_ENDPOINT_INPUT}
AWG_INTERFACE=awg0
LISTEN_HOST=0.0.0.0
LISTEN_PORT=8181
LOG_LEVEL=INFO
EOF

    chmod 600 .env
    log ".env created (permissions set to 600 — contains AGENT_TOKEN)."

    # shellcheck disable=SC1091
    source .env
fi

# --- 4. Build and start ---------------------------------------------------
log "Building images (this pulls amneziavpn/amneziawg-go:2.0.0 the first time)..."
docker compose build

log "Starting containers..."
docker compose up -d --remove-orphans

log "Cleaning up dangling images left over from previous builds..."
docker image prune -f

# --- 5. Wait for the agent to actually respond ----------------------------
log "Waiting for node-agent to become healthy..."
HEALTHY=0
for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:${LISTEN_PORT:-8181}/health" > /dev/null 2>&1; then
        HEALTHY=1
        break
    fi
    sleep 2
done

if [ "$HEALTHY" -ne 1 ]; then
    err "node-agent did not become healthy within 60 seconds."
    err "Check logs with: docker compose logs node-agent"
    exit 1
fi

HEALTH_JSON="$(curl -fsS "http://127.0.0.1:${LISTEN_PORT:-8181}/health")"
log "node-agent is up: ${HEALTH_JSON}"

if ! echo "$HEALTH_JSON" | grep -q '"awg_container_running": *true'; then
    warn "node-agent is reachable, but awg_container_running is not true."
    warn "Check: docker compose logs amnezia-awg2"
fi

# --- 6. Final instructions -------------------------------------------------
echo ""
log "Node installation complete."
echo ""
echo "  Add this node in the panel with:"
echo "    hostname:    $(hostname -I 2>/dev/null | awk '{print $1}' || echo '<this server'"'"'s reachable IP>')"
echo "    agent_port:  ${LISTEN_PORT:-8181}"
echo "    listen_port: ${AWG_LISTEN_PORT:-55632}"
echo "    agent_token: ${AGENT_TOKEN}"
echo ""
warn "agent_token is a secret — copy it now, it will not be printed again by this script"
warn "(it is stored in .env on this node if you need it later: cat .env | grep AGENT_TOKEN)"
echo ""
log "Make sure port ${LISTEN_PORT:-8181}/tcp is reachable from the panel's IP only"
log "(firewall allowlist), and port ${AWG_LISTEN_PORT:-55632}/udp is open to the internet"
log "for actual VPN clients."
