#!/usr/bin/env bash
#
# Installs the AWG-RT panel: postgres + redis + the panel app itself.
#
# Run this ON THE MAIN SERVER, from inside the panel/ directory of
# this repo:
#
#   cd Vodkinnet-AWG-RT/panel
#   sudo ./install.sh
#
# Safe to re-run: if .env already exists, it is reused as-is rather
# than regenerated — regenerating POSTGRES_PASSWORD or JWT_SECRET on
# an existing install would lock the panel out of its own database
# and invalidate every admin's session.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

log()  { echo -e "\033[1;34m[install-panel]\033[0m $*"; }
warn() { echo -e "\033[1;33m[install-panel]\033[0m $*"; }
err()  { echo -e "\033[1;31m[install-panel]\033[0m $*" >&2; }

# --- 1. Root check ---------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (or with sudo)."
    exit 1
fi

# --- 2. Docker + Compose plugin check/install -------------------------------
if ! command -v docker &> /dev/null; then
    log "Docker not found — installing via get.docker.com convenience script."
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
else
    log "Docker already installed: $(docker --version)"
fi

if ! docker compose version &> /dev/null; then
    err "Docker is installed but the 'docker compose' plugin is missing."
    err "Reinstall via get.docker.com, or install docker-compose-plugin"
    err "manually for your distro, then re-run this script."
    exit 1
fi
log "docker compose available: $(docker compose version --short)"

# --- 3. .env setup -----------------------------------------------------------
if [ -f .env ]; then
    warn ".env already exists — reusing it as-is."
    warn "Skipping secret generation. If you need to rotate JWT_SECRET or"
    warn "POSTGRES_PASSWORD, do it deliberately (rotating JWT_SECRET logs"
    warn "out every admin; rotating POSTGRES_PASSWORD requires updating it"
    warn "in the running postgres container too) — this script won't do"
    warn "that for you automatically to avoid a surprise lockout."
    # shellcheck disable=SC1091
    source .env
else
    log "No .env found — generating one with fresh secrets."

    GENERATED_PG_PASSWORD="$(openssl rand -hex 24)"
    GENERATED_JWT_SECRET="$(openssl rand -hex 32)"

    # DATABASE_URL is written out with the real password inlined —
    # .env files are NOT shell scripts, so ${POSTGRES_PASSWORD}-style
    # interpolation inside the file would NOT be expanded by the
    # Python app reading it (pydantic-settings reads .env as flat
    # key=value pairs, no variable substitution). Docker Compose DOES
    # do its own ${VAR} substitution for values used directly in
    # docker-compose.yml (like POSTGRES_PASSWORD below), which is a
    # separate mechanism from what the app sees — hence writing the
    # password twice here, deliberately, not a typo.
    cat > .env << EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

POSTGRES_USER=awgrt
POSTGRES_PASSWORD=${GENERATED_PG_PASSWORD}
POSTGRES_DB=awgrt
DATABASE_URL=postgresql+asyncpg://awgrt:${GENERATED_PG_PASSWORD}@postgres:5432/awgrt

REDIS_URL=redis://redis:6379/0
PEER_CONFIG_TTL_SECONDS=172800

JWT_SECRET=${GENERATED_JWT_SECRET}

MONITORING_INTERVAL_SECONDS=180
HANDSHAKE_STALE_AFTER_SECONDS=300
HANDSHAKE_DOWN_AFTER_SECONDS=900

LOG_LEVEL=INFO
APP_ENV=production
EOF

    chmod 600 .env
    log ".env created (permissions set to 600 — contains DB password and JWT secret)."

    # shellcheck disable=SC1091
    source .env
fi

# --- 4. Build and start -------------------------------------------------------
log "Building the panel image..."
docker compose build

log "Starting postgres and redis..."
docker compose up -d postgres redis

log "Waiting for postgres to become healthy..."
for _ in $(seq 1 30); do
    STATUS="$(docker inspect --format='{{.State.Health.Status}}' awgrt-postgres 2>/dev/null || echo "starting")"
    if [ "$STATUS" = "healthy" ]; then
        break
    fi
    sleep 2
done
if [ "$STATUS" != "healthy" ]; then
    err "postgres did not become healthy in time. Check: docker compose logs postgres"
    exit 1
fi
log "postgres is healthy."

log "Starting the panel (this also runs 'alembic upgrade head' on boot)..."
docker compose up -d panel

log "Waiting for the panel to respond..."
HEALTHY=0
for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:8000/docs" > /dev/null 2>&1; then
        HEALTHY=1
        break
    fi
    sleep 2
done

if [ "$HEALTHY" -ne 1 ]; then
    err "Panel did not respond within 60 seconds. Check: docker compose logs panel"
    exit 1
fi
log "Panel is up and responding on 127.0.0.1:8000."

# --- 5. First admin account ----------------------------------------------------
echo ""
read -rp "Create the first admin account now? [Y/n] " CREATE_ADMIN_ANSWER
CREATE_ADMIN_ANSWER="${CREATE_ADMIN_ANSWER:-Y}"
if [[ "$CREATE_ADMIN_ANSWER" =~ ^[Yy] ]]; then
    docker compose exec panel python3 scripts/create_admin.py
else
    log "Skipped. Create one later with:"
    log "  docker compose exec panel python3 scripts/create_admin.py"
fi

# --- 6. Final instructions --------------------------------------------------
echo ""
log "Panel installation complete."
echo ""
echo "  The panel is listening on 127.0.0.1:8000 (localhost only)."
echo "  Put your existing nginx/Caddy reverse proxy in front of it with"
echo "  TLS, e.g.:"
echo ""
echo "    proxy_pass http://127.0.0.1:8000;"
echo ""
echo "  Once that's set up, log in at https://<your-chosen-domain>/login"
echo ""
log "To add a node, first run node-agent/install.sh on that node, then"
log "use the panel's 'Add node' form with the hostname/port/token it prints."
